.TH GENL 8
.SH NAME
genl \- generic netlink utility frontend
.SH SYNOPSIS
.B genl
.RI [ options ] { ctrl } [ help ]
.SH DESCRIPTION
This manual page documents briefly the
.B genl
command.
.PP
\fBgenl\fP utility provides a simple frontend to the generic netlink library.
.SH OPTIONS
genl supports the following options.
.TP
.B \-h, \-help
Show summary of options.
.TP
.B \-V, \-Version
Show version of program.
.TP
.B \-s, \-stats, \-statistics
Show object statistics.
.TP
.B \-d, \-details
Show object details.
.TP
.B \-r, \-raw
Dump raw output only.
.SH SEE ALSO
.BR ip (8)
.br
.SH AUTHOR
genl was written by Jamal Hadi Salim <hadi@cyberus.ca>.
.PP
This manual page was written by Petr Sabata <contyk@redhat.com>.
